// Data Memory (DMEM)
// 1KB (256 words x 32 bits) asynchronous read / synchronous write memory module.
module dmem (
    input  wire        clk,
    input  wire [31:0] addr,       // Target byte address generated by the ALU
    input  wire [31:0] write_data, // Data payload to write into memory (from rs2)
    input  wire        mem_read,   // Read enable signal (from Decoder)
    input  wire        mem_write,  // Write enable signal (from Decoder)
    output wire [31:0] read_data   // Data output bus (to Register File writeback)
);
    // Storage array: 256 words (32-bit width = 1KB total capacity)
    reg [31:0] data_mem [0:255];
    // Byte address to word index conversion
    // Dropping the lower 2 offset bits (addr[1:0]) divides the byte address by 4.
    wire [7:0] word_addr = addr[9:2];
    // Combinational (asynchronous) Read Port
    // If mem_read is high, output the word at the calculated address;
    // otherwise, output high-impedance / 0 to prevent bogus data propagation.
    assign read_data = (mem_read) ? data_mem[word_addr] : 32'b0;
    // Synchronous Write Port
    // Writes occur on the rising clock edge when mem_write is active.
    always @(posedge clk) begin
        if (mem_write) begin
            data_mem[word_addr] <= write_data;
        end
    end
endmodule
